---

- name: Get the version information of the latest release of Vagrant
  uri:
    url: https://api.github.com/repos/hashicorp/vagrant/tags
    return_content: true
    body_format: json
  register: vagrant_get_latest_version

- name: Ensure the vagrant_version variable is set
  set_fact:
    vagrant_version: "{{ vagrant_get_latest_version.json.0.name | regex_replace('^v', '') }}"
